### ISSUE TITLE
Add a config for LGTM.com

### ISSUE THREAD

**Issue by artem-smotrakov** [eclipse-ee4j/eclipselink#942]
LGTM.com offers static analysis for open-source project. It helps catching issues earlier (including security ones). This is based on CodeQL engine. Currently, a report for EclipseLink is available but it doesn't see to be correct. In particular, it doesn't contain any Java sources which is suspicious:

https://lgtm.com/projects/g/eclipse-ee4j/eclipselink/alerts/?mode=list

Instead, the report shows findings in the Python code that seems to be used only for testing purposes. Therefore, the current grade `E` (which is bad) doesn't look correct.

Adding a config file for LGTM.com should fix this:

https://help.semmle.com/lgtm-enterprise/user/help/lgtm.yml-configuration-file.html#language_block

I think the config may look like the following:

```
path_classifiers:

  # exclude tests
  test:
    - "**/src/test/**"
    - "**/src/it/**"
    - "**/*.test/**"
    - "**/tests/**"
    - performance

  # exclude docs
  docs:
    - about.html
    - license.html
    - readme.html

extraction:
  java:
    index:
      build_command: mvn -DskipTests clean package
```

I can open a pull request that adds a config like above. Once a correct report at LGTM.com is available, I can also triage findings and fix major ones.
